# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EY0MGLkH92ezD2cb4qRVgS3VfFUxDHBp
"""

!pip install -q streamlit
!npm install localtunnel

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from tensorflow import keras
# from tensorflow.keras.preprocessing import image
# import numpy as np
# import os
# 
# # Load model from Google Drive
# model = keras.models.load_model('/content/drive/MyDrive/plant_disease_model.keras')
# 
# # Class names (replace with yours)
# class_names = [...]  # Your list of class names
# 
# def predict_disease(img_path):
#     img = image.load_img(img_path, target_size=(256, 256))
#     img_array = image.img_to_array(img)
#     img_array = np.expand_dims(img_array, axis=0)
#     img_array /= 255.
#     prediction = model.predict(img_array)
#     return class_names[np.argmax(prediction[0])]
# 
# st.title('Plant Disease Detection')
# uploaded_file = st.file_uploader("Upload a leaf image", type=["jpg", "png", "jpeg"])
# 
# if uploaded_file:
#     temp_path = "temp_image.jpg"
#     with open(temp_path, "wb") as f:
#         f.write(uploaded_file.getbuffer())
#     st.image(uploaded_file)
#     prediction = predict_disease(temp_path)
#     st.success(f"Predicted Disease: **{prediction}**")
#

!streamlit run app.py &>/content/logs.txt &
!npx localtunnel --port 8501